export default {
  1: "Blinded",
  2: "Dazed",
  3: "Deafened",
  4: "Dominated",
  5: "Dying",
  6: "Grabbed",
  7: "Helpless",
  8: "Immobilized",
  9: "Marked",
  10: "Petrified",
  11: "Prone",
  12: "Removed from play",
  13: "Restrained",
  14: "Slowed",
  15: "Stunned",
  16: "Surprised",
  17: "Unconscious",
  18: "Weakened",
  BLINDED: 1,
  DAZED: 2,
  DEAFENED: 3,
  DOMINATED: 4,
  DYING: 5,
  GRABBED: 6,
  HELPLESS: 7,
  IMMOBILIZED: 8,
  MARKED: 9,
  PETRIFIED: 10,
  PRONE: 11,
  REMOVED_FROM_PLAY: 12,
  RESTRAINED: 13,
  SLOWED: 14,
  STUNNED: 15,
  SURPRISED: 16,
  UNCONSCIOUS: 17,
  WEAKENED: 18,
};
